#ifndef I_DR4_KEY_CODE
#define I_DR4_KEY_CODE

namespace dr4 {

enum KeySyms {
    SYM_UNKNOWN = 0,

    SYM_RETURN = '\r',
    SYM_ESCAPE = '\x1B',
    SYM_BACKSPACE = '\b',
    SYM_TAB = '\t',
    SYM_SPACE = ' ',
    SYM_EXCLAIM = '!',
    SYM_QUOTEDBL = '"',
    SYM_HASH = '#',
    SYM_PERCENT = '%',
    SYM_DOLLAR = '$',
    SYM_AMPERSAND = '&',
    SYM_QUOTE = '\'',
    SYM_LEFTPAREN = '(',
    SYM_RIGHTPAREN = ')',
    SYM_ASTERISK = '*',
    SYM_PLUS = '+',
    SYM_COMMA = ',',
    SYM_MINUS = '-',
    SYM_PERIOD = '.',
    SYM_SLASH = '/',
    SYM_0 = '0',
    SYM_1 = '1',
    SYM_2 = '2',
    SYM_3 = '3',
    SYM_4 = '4',
    SYM_5 = '5',
    SYM_6 = '6',
    SYM_7 = '7',
    SYM_8 = '8',
    SYM_9 = '9',
    SYM_COLON = ':',
    SYM_SEMICOLON = ';',
    SYM_LESS = '<',
    SYM_EQUALS = '=',
    SYM_GREATER = '>',
    SYM_QUESTION = '?',
    SYM_AT = '@',

    SYM_LEFTBRACKET = '[',
    SYM_BACKSLASH = '\\',
    SYM_RIGHTBRACKET = ']',
    SYM_CARET = '^',
    SYM_UNDERSCORE = '_',
    SYM_BACKQUOTE = '`',
    SYM_a = 'a',
    SYM_b = 'b',
    SYM_c = 'c',
    SYM_d = 'd',
    SYM_e = 'e',
    SYM_f = 'f',
    SYM_g = 'g',
    SYM_h = 'h',
    SYM_i = 'i',
    SYM_j = 'j',
    SYM_k = 'k',
    SYM_l = 'l',
    SYM_m = 'm',
    SYM_n = 'n',
    SYM_o = 'o',
    SYM_p = 'p',
    SYM_q = 'q',
    SYM_r = 'r',
    SYM_s = 's',
    SYM_t = 't',
    SYM_u = 'u',
    SYM_v = 'v',
    SYM_w = 'w',
    SYM_x = 'x',
    SYM_y = 'y',
    SYM_z = 'z',
};

enum ScanCodes {
    SDL_SCANCODE_UNKNOWN = 0,

    SDL_SCANCODE_A = 4,
    SDL_SCANCODE_B = 5,
    SDL_SCANCODE_C = 6,
    SDL_SCANCODE_D = 7,
    SDL_SCANCODE_E = 8,
    SDL_SCANCODE_F = 9,
    SDL_SCANCODE_G = 10,
    SDL_SCANCODE_H = 11,
    SDL_SCANCODE_I = 12,
    SDL_SCANCODE_J = 13,
    SDL_SCANCODE_K = 14,
    SDL_SCANCODE_L = 15,
    SDL_SCANCODE_M = 16,
    SDL_SCANCODE_N = 17,
    SDL_SCANCODE_O = 18,
    SDL_SCANCODE_P = 19,
    SDL_SCANCODE_Q = 20,
    SDL_SCANCODE_R = 21,
    SDL_SCANCODE_S = 22,
    SDL_SCANCODE_T = 23,
    SDL_SCANCODE_U = 24,
    SDL_SCANCODE_V = 25,
    SDL_SCANCODE_W = 26,
    SDL_SCANCODE_X = 27,
    SDL_SCANCODE_Y = 28,
    SDL_SCANCODE_Z = 29,

    SDL_SCANCODE_1 = 30,
    SDL_SCANCODE_2 = 31,
    SDL_SCANCODE_3 = 32,
    SDL_SCANCODE_4 = 33,
    SDL_SCANCODE_5 = 34,
    SDL_SCANCODE_6 = 35,
    SDL_SCANCODE_7 = 36,
    SDL_SCANCODE_8 = 37,
    SDL_SCANCODE_9 = 38,
    SDL_SCANCODE_0 = 39,

    SDL_SCANCODE_RETURN = 40,
    SDL_SCANCODE_ESCAPE = 41,
    SDL_SCANCODE_BACKSPACE = 42,
    SDL_SCANCODE_TAB = 43,
    SDL_SCANCODE_SPACE = 44,

    SDL_SCANCODE_MINUS = 45,
    SDL_SCANCODE_EQUALS = 46,
    SDL_SCANCODE_LEFTBRACKET = 47,
    SDL_SCANCODE_RIGHTBRACKET = 48,
    SDL_SCANCODE_BACKSLASH = 49,

    SDL_SCANCODE_SEMICOLON = 51,
    SDL_SCANCODE_APOSTROPHE = 52,

    SDL_SCANCODE_COMMA = 54,
    SDL_SCANCODE_PERIOD = 55,
    SDL_SCANCODE_SLASH = 56,

    SDL_SCANCODE_CAPSLOCK = 57,

    SDL_SCANCODE_F1 = 58,
    SDL_SCANCODE_F2 = 59,
    SDL_SCANCODE_F3 = 60,
    SDL_SCANCODE_F4 = 61,
    SDL_SCANCODE_F5 = 62,
    SDL_SCANCODE_F6 = 63,
    SDL_SCANCODE_F7 = 64,
    SDL_SCANCODE_F8 = 65,
    SDL_SCANCODE_F9 = 66,
    SDL_SCANCODE_F10 = 67,
    SDL_SCANCODE_F11 = 68,
    SDL_SCANCODE_F12 = 69,

    SDL_SCANCODE_PRINTSCREEN = 70,
    SDL_SCANCODE_SCROLLLOCK = 71,
    SDL_SCANCODE_PAUSE = 72,
    SDL_SCANCODE_INSERT = 73,

    SDL_SCANCODE_HOME = 74,
    SDL_SCANCODE_PAGEUP = 75,
    SDL_SCANCODE_DELETE = 76,
    SDL_SCANCODE_END = 77,
    SDL_SCANCODE_PAGEDOWN = 78,
    SDL_SCANCODE_RIGHT = 79,
    SDL_SCANCODE_LEFT = 80,
    SDL_SCANCODE_DOWN = 81,
    SDL_SCANCODE_UP = 82,

    SDL_SCANCODE_NUMLOCKCLEAR = 83
};

enum KeyModes {
    MOD_NONE = 0x0000,
    MOD_LSHIFT = 0x0001,
    MOD_RSHIFT = 0x0002,
    MOD_LCTRL = 0x0040,
    MOD_RCTRL = 0x0080,
    MOD_LALT = 0x0100,
    MOD_RALT = 0x0200,
    MOD_CAPS = 0x2000,

    MOD_CTRL = MOD_LCTRL | MOD_RCTRL,
    MOD_SHIFT = MOD_LSHIFT | MOD_RSHIFT,
    MOD_ALT = MOD_LALT | MOD_RALT,
};

}

#endif // I_DR4_KEY_CODE